name: planetpieces_env
channels:
- conda-forge
dependencies:
- python=3.7
- numpy
- pandas
- xarray
- matplotlib
- rasterio
- ipython
- ipykernel
- pip
- keras
- seaborn
- scikit-learn
- pip:
    - tensorflow==2.0.0-rc0
